# Generated by Django 3.2.23 on 2024-03-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm_wells', '0004_alter_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='well_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]